version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Running tests in TestEnv"
      - npm test

artifacts:
  files:
    - '**/*'
